### ISSUE TITLE
リソースの宣言内で GetAttr を使用しているときに宣言していなくても対象を依存に含めるようにする

### ISSUE THREAD

**Issue by niwa-kazutomo** [gs2io/gs2-feedback#25]
```
  IdentifierDistributeUser:
    Type: GS2::Identifier::User
    Properties:
      Name: ${DistributeUserName}

  IdentifierDistributeUserAttachPolicy:
    Type: GS2::Identifier::AttachSecurityPolicy
    Properties:
      UserName: !GetAttr IdentifierDistributeUser.Item.Name
      SecurityPolicyId: grn:gs2::system:identifier:securityPolicy:AdministratorAccess
    DependsOn:
      - IdentifierDistributeUser
```

という定義がある場合

`UserName: !GetAttr IdentifierDistributeUser.Item.Name`

の存在によって

```
    DependsOn:
      - IdentifierDistributeUser
```

が不要になるようにする
